### ISSUE TITLE
install done with errors / load fixture fails

### ISSUE THREAD

**Issue by esion** [CaliOpen/caliopen-dev#23]
got some warnings & errors on install, 

~~~
Installing collected packages: Pygments, WebOb, amqp, bcrypt, cffi, cornice, cql, cqlengine, dateutils, gevent, greenlet, kombu, pycparser, pyramid, pyramid-jinja2, python-dateutil, python-memcached, pytz, redis, requests, simplejson, six, thrift, translationstring, venusian, waitress, zope.deprecation, zope.interface, gsmtpd, Chameleon, Mako
  Running setup.py install for Pygments
    
    Installing pygmentize script to /home/dey/workspace/caliopen/venv/bin
  Found existing installation: WebOb 1.4.1
    Uninstalling WebOb:
      Successfully uninstalled WebOb
  Running setup.py install for WebOb
    
    no previously-included directories found matching '*.pyc'
    no previously-included directories found matching '*.pyo'
  Found existing installation: amqp 1.4.6
    Uninstalling amqp:
      Successfully uninstalled amqp
  Rolling back uninstall of amqp
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/dey/workspace/caliopen/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/dey/workspace/caliopen/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 309, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/dey/workspace/caliopen/venv/local/lib/python2.7/site-packages/pip/req.py", line 1440, in install
    requirement.rollback_uninstall()
  File "/home/dey/workspace/caliopen/venv/local/lib/python2.7/site-packages/pip/req.py", line 604, in rollback_uninstall
    self.uninstalled.rollback()
  File "/home/dey/workspace/caliopen/venv/local/lib/python2.7/site-packages/pip/req.py", line 1864, in rollback
    pth.rollback()
AttributeError: 'str' object has no attribute 'rollback'

Storing debug log for failure in /home/dey/.pip/pip.log
running develop
~~~

I'm not sure it is important but fixtures cannot be loaded afterward

~~~
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1224: UserWarning: /home/dey/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/cassandra_driver-2.6.0rc1-py2.7-linux-x86_64.egg/cassandra/util.py:486: UserWarning: The blist library is not available, so a pure python list-based set will be used in place of blist.sortedset for set collection values. You can find the blist library here: https://pypi.python.org/pypi/blist/
Traceback (most recent call last):
  File "/home/workspace/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/home/workspace/caliopen/cli/caliopen/cli/cli.py", line 61, in main
    connect_storage()
  File "/home/workspace/caliopen/base/caliopen/base/helpers/connection.py", line 19, in connect_storage
    **kwargs)
TypeError: setup() got an unexpected keyword argument 'lazy_connect'
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1224: UserWarning: /home/dey/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/cassandra_driver-2.6.0rc1-py2.7-linux-x86_64.egg/cassandra/util.py:486: UserWarning: The blist library is not available, so a pure python list-based set will be used in place of blist.sortedset for set collection values. You can find the blist library here: https://pypi.python.org/pypi/blist/
Traceback (most recent call last):
  File "/home/workspace/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/home/workspace/caliopen/cli/caliopen/cli/cli.py", line 61, in main
    connect_storage()
  File "/home/workspace/caliopen/base/caliopen/base/helpers/connection.py", line 19, in connect_storage
    **kwargs)
TypeError: setup() got an unexpected keyword argument 'lazy_connect'
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1224: UserWarning: /home/dey/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
/home/workspace/caliopen/venv/local/lib/python2.7/site-packages/cassandra_driver-2.6.0rc1-py2.7-linux-x86_64.egg/cassandra/util.py:486: UserWarning: The blist library is not available, so a pure python list-based set will be used in place of blist.sortedset for set collection values. You can find the blist library here: https://pypi.python.org/pypi/blist/
Traceback (most recent call last):
  File "/home/workspace/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/home/workspace/caliopen/cli/caliopen/cli/cli.py", line 61, in main
    connect_storage()
  File "/home/workspace/caliopen/base/caliopen/base/helpers/connection.py", line 19, in connect_storage
    **kwargs)
TypeError: setup() got an unexpected keyword argument 'lazy_connect'
~~~
~~~

**Comment by gdchamal** [comment]
strange that this lazy_connect argument to setup cassandra connection is not valid in this driver release (2.6rc1: https://github.com/datastax/python-driver/blob/48ec3ebee2/cassandra%2Fcqlengine%2Fconnection.py)

@esion can you provide a pip freeze output to ensure not a conflicting cqlengine package and version.

**Comment by esion** [comment]
I do not speak fluent python. So I did that : 

~~~python 
$ pip freeze
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/commands/freeze.py", line 73, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/local/lib/python2.7/dist-packages/pip-1.4.1-py2.7.egg/pip/__init__.py", line 194, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError
~~~

Does not sound good :s . But I try also in venv : 

~~~bash
$ source venv/bin/activate
$ pip freeze              
Chameleon==2.22
Jinja2==2.7.3
Mako==1.0.1
MarkupSafe==0.23
PasteDeploy==1.5.2
PyYAML==3.11
Pygments==1.6
WebOb==1.4
amqp==1.4.5
anyjson==0.3.3
argparse==1.2.1
bcrypt==1.0.2
-e git+https://github.com/CaliOpen/caliopen.api.base.git@6bbca7c3210d700788d91b91a3e8c7a01a8a8719#egg=caliopen.api.base-master
-e git+https://github.com/CaliOpen/caliopen.api.message.git@b67f9463e484cfab7adea629d9c899b03bc4be10#egg=caliopen.api.message-master
-e git+https://github.com/CaliOpen/caliopen.api.user.git@0276d0e5ccf8d63adb7dd4438d67c0ff2c5bc3ae#egg=caliopen.api.user-master
-e git+https://github.com/CaliOpen/caliopen.base.git@30a4c27d4ad1c3b72d4d6ddaf00aa876fff09664#egg=caliopen.base-master
-e git+https://github.com/CaliOpen/caliopen.base.message.git@f2b3637647acdb4d83e004e6901aa217e9f16256#egg=caliopen.base.message-master
-e git+https://github.com/CaliOpen/caliopen.base.user.git@2351f24bae22fe48a03f28465c62a204829079c6#egg=caliopen.base.user-master
-e git+https://github.com/CaliOpen/caliopen.cli.git@0cdc7589c9c418d744a540ca20f0a0e57c74c665#egg=caliopen.cli-master
-e git+https://github.com/CaliOpen/caliopen.messaging.git@2825b19640cad78f664891b723e657745c4344f3#egg=caliopen.messaging-master
-e git+https://github.com/CaliOpen/caliopen.smtp.git@33bb56631a2d6ba8ac97912c15e5175c39e66893#egg=caliopen.smtp-master
-e git+https://github.com/CaliOpen/caliopen.web.git@024099cbc885a160a333ea94b69c68d76057cd5c#egg=caliopen.web-master
cassandra-driver==2.6.0rc1
cffi==0.8.2
cornice==0.16.2
cql==1.4.0
cqlengine==0.12.0
dateutils==0.6.6
elasticsearch==1.5.0
elasticsearch-dsl==0.0.4
futures==3.0.2
gevent==1.0.1
greenlet==0.4.2
gsmtpd==0.0.3
ipython==3.1.0
kombu==3.0.19
mock==1.0.1
pycparser==2.10
pyramid==1.4.6
pyramid-jinja2==2.3.2
pyramid-kvs==0.2.2
python-dateutil==2.2
python-memcached==1.53
pytz==2014.4
redis==2.10.1
repoze.lru==0.6
requests==2.3.0
schematics==1.0.4
simplejson==3.5.2
six==1.9.0
thrift==0.9.1
translationstring==1.1
urllib3==1.10.4
venusian==1.0a8
waitress==0.8.9
wsgiref==0.1.2
zope.deprecation==4.1.1
zope.interface==4.1.1
~~~

**Comment by gdchamal** [comment]
OK there is clearly a problem with cqlengine-0.12. I'll remove completly dependency to replace with version included in cassandra driver package.

You can remove this version (in virtualenv pip remove cqlengine) and try reinstalling a newest version, My pip give me a version 0.21 (that is correct) when trying to install from scratch

**Comment by esion** [comment]
I suppose the requirements in web repo is not good : https://github.com/CaliOpen/caliopen.web/blob/master/requirements.txt#L15 .

**Comment by gdchamal** [comment]
yes you right :/

**Comment by gdchamal** [comment]
Issue open : https://github.com/CaliOpen/caliopen.web/issues/23 will address it quickly

**Comment by gdchamal** [comment]
Fixed dependency version
