### ISSUE TITLE
Issue while logging in

### ISSUE THREAD

**Issue by pascalduez** [CaliOpen/caliopen-dev#24]
On a fresh clone and `./bin/install`:

```
./bin/start  
Activate virtualenv
Start containers
Creating bin_redis_1...
Creating bin_rabbitmq_1...
Creating bin_elasticsearch_1...
Creating bin_cassandra_1...
Have to wait for cassandra to be up
Start server
Starting subprocess with file monitor
2015-08-24 19:12:15,725 DEBUG [caliopen.api.user.config][MainThread] Loading user API
2015-08-24 19:12:15,747 DEBUG [caliopen.api.user.config][MainThread] Loading contact API
2015-08-24 19:12:15,807 DEBUG [caliopen.api.message.config][MainThread] Loading message API
2015-08-24 19:12:15,825 DEBUG [caliopen.api.message.config][MainThread] Loading thread API
2015-08-24 19:12:15,832 DEBUG [caliopen.web.config][MainThread] Will serve "frontend" assets from /home/pascal/caliopen/web/../frontend/dist/frontend/
2015-08-24 19:12:15,833 DEBUG [caliopen.web.views.app.config][MainThread] Declare open.web.app routes
2015-08-24 19:12:15,838 DEBUG [caliopen.web.views.user.config][MainThread] Declare open.web.user routes
Starting server in PID 32750.
serving on http://0.0.0.0:6543
2015-08-24 19:12:27,722 DEBUG [caliopen.web.views][Dummy-2] http://0.0.0.0:6543/signin/
2015-08-24 19:12:30,748 DEBUG [caliopen.web.authentication.validation][Dummy-3] 'NoneType' object has no attribute '_consistency'
2015-08-24 19:12:30,748 DEBUG [caliopen.web.authentication.validation][Dummy-3] 'NoneType' object has no attribute '_consistency'
2015-08-24 19:12:30,749 ERROR [waitress][Dummy-3] Exception when serving /signin/
Traceback (most recent call last):
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 40, in excview_tween
    response = view_callable(exc, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 377, in viewresult_to_response
    result = view(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 588, in __call__
    return view(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 321, in attr_view
    return view(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 297, in predicate_wrapper
    return view(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 347, in rendered_view
    result = view(context, request)
  File "/home/pascal/caliopen/venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 469, in _class_requestonly_view
    response = getattr(inst, attr)()
  File "/home/pascal/caliopen/web/caliopen/web/views/user/signin.py", line 40, in handle_signin
    authentication = validate(self.username, self.password)
  File "/home/pascal/caliopen/web/caliopen/web/authentication/validation.py", line 120, in validate
    raise exc
AttributeError: 'NoneType' object has no attribute '_consistency'
```

Note: I had to run `./bin/install` several times to get everything installed "correctly" and the stack to start.

**Comment by themouette** [comment]
Authentication changed lately, I think caliopen.web is broken.

You can use the [caliopen.frontend](https://github.com/CaliOpen/caliopen.frontend) repository standalone though.

**Comment by gdchamal** [comment]
Yes caliopen.web is broken the way it use authentication. Will try to make it work again until we migrate this component to a node.js one as we discussed with @themouette lately

**Comment by gdchamal** [comment]
caliopen.web change, this issue is no more valid
