### ISSUE TITLE
load fixtures 

### ISSUE THREAD

**Issue by esion** [CaliOpen/caliopen-dev#35]
since api is launched within a container the load_fixtures command fails : 

~~~
root@poc2:/opt# bin/load-fixtures                                                                                                                                      [14/1955]
Traceback (most recent call last):
  File "/opt/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/opt/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/opt/cli/caliopen/cli/commands/setup_storage.py", line 24, in setup_storage
    sync_table(kls._model_class)
  File "build/bdist.linux-x86_64/egg/cqlengine/management.py", line 108, in sync_table
  File "build/bdist.linux-x86_64/egg/cqlengine/management.py", line 238, in get_fields
  File "build/bdist.linux-x86_64/egg/cqlengine/connection.py", line 108, in execute
  File "cassandra/cluster.py", line 1569, in cassandra.cluster.Session.execute (cassandra/cluster.c:26930)
  File "cassandra/cluster.py", line 3122, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:59993)
cassandra.InvalidRequest: code=2200 [Invalid query] message="unconfigured table schema_columns"
Traceback (most recent call last):
  File "/opt/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/opt/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/opt/cli/caliopen/cli/commands/create_user.py", line 20, in create_user
    user = User.create(param)
  File "/opt/base.user/caliopen/base/user/core/user.py", line 107, in create
    if cls.find(name=user.name):
  File "/opt/base/caliopen/base/core/base.py", line 112, in find
    return [cls(x) for x in objs]
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 339, in __iter__
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 317, in _execute_query
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 251, in _execute
  File "build/bdist.linux-x86_64/egg/cqlengine/connection.py", line 108, in execute
  File "cassandra/cluster.py", line 1569, in cassandra.cluster.Session.execute (cassandra/cluster.c:26930)
  File "cassandra/cluster.py", line 3122, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:59993)
cassandra.InvalidRequest: code=2200 [Invalid query] message="No supported secondary index found for the non primary key columns restrictions"
Traceback (most recent call last):
  File "/opt/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli==0.0.1', 'console_scripts', 'caliopen')()
  File "/opt/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/opt/cli/caliopen/cli/commands/import_email.py", line 46, in import_email
    user = User.by_name(email)
  File "/opt/base.user/caliopen/base/user/core/user.py", line 129, in by_name
    res = cls.find(name=name)
  File "/opt/base/caliopen/base/core/base.py", line 112, in find
    return [cls(x) for x in objs]
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 339, in __iter__
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 317, in _execute_query
  File "build/bdist.linux-x86_64/egg/cqlengine/query.py", line 251, in _execute
  File "build/bdist.linux-x86_64/egg/cqlengine/connection.py", line 108, in execute
  File "cassandra/cluster.py", line 1569, in cassandra.cluster.Session.execute (cassandra/cluster.c:26930)
  File "cassandra/cluster.py", line 3122, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:59993)
cassandra.InvalidRequest: code=2200 [Invalid query] message="No supported secondary index found for the non primary key columns restrictions"
~~~

I got this error on the not large scaled vm, so I may have things to try... stay tune ;)

**Comment by gdchamal** [comment]
related to a change in secondary index functionalities in latest cassandra releases.

Work in progress here https://github.com/CaliOpen/caliopen.base.user/tree/features/valid-username for a better username management, failure happen around that logic, will fix in that branch

**Comment by gdchamal** [comment]
valid-username branch merged and fix this issue

**Comment by esion** [comment]
works fine. 

it is required to remove .data before
