### ISSUE TITLE
load_fixtures fails "No module named user.core"

### ISSUE THREAD

**Issue by bortzmeyer** [CaliOpen/caliopen-dev#44]
```
vps211695:~/caliopen/bin % ./load-fixtures -h        
Traceback (most recent call last):
  File "/home/bortzmeyer/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli', 'console_scripts', 'caliopen')()
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/commands/setup_storage.py", line 13, in setup_storage
    from caliopen.base.user.core import User
ImportError: No module named user.core
Traceback (most recent call last):
  File "/home/bortzmeyer/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli', 'console_scripts', 'caliopen')()
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/commands/create_user.py", line 10, in create_user
    from caliopen.base.user.core import User
ImportError: No module named user.core
Traceback (most recent call last):
  File "/home/bortzmeyer/caliopen/venv/bin/caliopen", line 9, in <module>
    load_entry_point('caliopen.cli', 'console_scripts', 'caliopen')()
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/cli.py", line 63, in main
    func(**kwargs)
  File "/home/bortzmeyer/caliopen/cli/caliopen/cli/commands/import_email.py", line 22, in import_email
    from caliopen.base.user.core import User
ImportError: No module named user.core
```

The pull request in #40 is a bit better. When on the branch integration-script, it goes until:

```
Removing intermediate container cc5fd8d01143
Successfully built 19296e10a460
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: caliopen.cli==0.0.1
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: caliopen.cli==0.0.1
Traceback (most recent call last):
  File "/usr/local/bin/caliopen", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: caliopen.cli==0.0.1
vps211695:~/caliopen-exp/bin %
```

**Comment by iamdey** [comment]
There's a strange behavior that makes the cli container unstable.

Well this could be fixed with the following commands

```
cd bin
docker-compose run cli /bin/bash
# then in the container:
python setup.py develop
exit
# then reload
./load-fixtures
```
